[workspace]
resolver = "3"
members = ["influencer", "influencer-cli"]

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Kira Paul <k@cyra.pink>"]
license = "MIT"

[workspace.dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
tungstenite = "0.27.0"
